### ISSUE TITLE
💡 [FEAT] Make updating the due date a little bit easier by pre-selecting the text of the last date once "d" is pressed. 

### ISSUE THREAD

**Issue by voxcon** [kraanzu/dooit#117] opened 2023-05-11 18:28 UTC
Dislaimer: Sorry for opening another feature request, but don't worry this one should be fixable within a couple of minutes :) 

**Is your feature request related to a problem? Please describe.** 
Currently if you want to modify the due date of a ToDo you firstly need to press "d", then remove all the text specifying the last due date before you can enter the new due date. The step of having to delet the text of the previous due date could be skipped if the text of the last due date would be pre-selected once "d" is pressed. This way you could simply delete the old due date text by entering a new one without having to manually delete the old date text. 

**Describe the solution you'd like**  
If you want to change the due date of a ToDo, you currently need to do the following things: 
- press "d"
- delete old due date text manually
- enter new due date

By preselecting the old due date text after pressing "d" the step of having to manually delete the old due date could be skipped.

-press "d" -> automatically pre-select old due date text
- enter new due date (this automatically replaces the old due date text)

**Describe alternatives you've considered**  🧐
None.

**Additional context** 
This would be a small workflow / usability improvement.

**Comment by kraanzu** [comment] 2023-05-12 03:54
No Problem @voxcon , I guess it's a duplicate of #111 so I'll close this one :)

**Closed by kraanzu** 2023-05-12 03:54 UTC
Labels: enhancement
