### ISSUE TITLE
💡 [FEAT] [BUG] Alt+F, Alt+B and Alt+D shortcut for moving cursor and deleting

### ISSUE THREAD

**Issue by fiftyfathoms** [kraanzu/dooit#72] opened 2022-10-13 09:53 UTC
**Describe the bug** 🐛
Alt+F and Alt+B keyboard shortcuts are typically used in most terminal environments to move forward and backward one word at a time.  This works in bash and vim (insert mode) for example. Using these shortcuts in the insert mode of dooit causes the programme to crash and the terminal becoming non-responsive.   

The same can be said for Alt+W and Alt+D. Alt+W in dooit delivers what it should, but Alt+D causes crash.

**Expected behavior**  🤔 
Since some vim shortcuts are defined to work for navigation inside dooit, I suggest these keyboard shortcuts are defined to achieve their intended functionality:
- Alt+F: move one word forward
- Alt+B: move one word backward
- Alt+D: delete the next word

**Desktop (please complete the following information):**  🤖
 - OS: WSL2 on Windows 10 and Windows 11 with both Ubuntu 18.04 and OpenSUSE Tumbleweed
 - Version: 0.2.1

**Comment by kraanzu** [comment] 2022-10-13 15:29
Hmm... In my case dooit hangs with any key combination involving `Alt` key.
But actually, the issue is not related to dooit but the TUI framework that it relies on which is textual.
There will be a new release of textual on the 24th of October. Let's hope that fixes this issue :)

I'll keep this issue open for now and try investigating more on this :smile: 
I'll push a new release soon too which will be make dooit much more customisable and usable

**Comment by fiftyfathoms** [comment] 2022-10-14 09:22
Thanks for the quick reply and the effort you put into maintaining and developing this amazing tool. I keep fingers crossed for the issue to be fixed by then.  
Do you recommend make a bug fix request at textual? Because I couldn't find any open or closed issue regarding this problem.

**Comment by kraanzu** [comment] 2022-10-14 12:25
> Do you recommend make a bug fix request at textual? 

Yeah, you sure can! 
If you want any kind of help I'll be happy to be of assistance 😄

**Comment by kraanzu** [comment] 2023-03-02 08:56
Looks like the `Alt` key is not recognized by textual ([here](https://textual.textualize.io/guide/input/#key))
In my case, it's blocking other keys until I press escape :( and then the alt key converts to the caret symbol (^)

I'll close this issue as this can't be fixed. I'll be sure to mention in case textual has a fix for this :)

**Closed by kraanzu** 2023-03-02 08:56 UTC
Labels: bug
