### ISSUE TITLE
💡 [FEAT] Keybinding for paste

### ISSUE THREAD

**Issue by sathishmanohar** [kraanzu/dooit#102] opened 2023-03-14 06:35 UTC
Right now, `y` yanks the current description and `Ctrl+v` pastes the text only while in `INSERT` mode. It isn't vim like, It'll be great if I can paste in `NORMAL` mode with `y` and then `p`. While you are at it. You can also look into the possibility of implementing it as the following.

`y` for yank description
`Y` for yank task with description due and urgency

**Comment by kraanzu** [comment] 2023-03-15 18:09
> Y for yank task with description due and urgency

Yes there was also a PR for this #78 but I closed that since the development stopped :(
I'm currently optimizing the rendering of todos and can implement this after that. Should be pretty easy :)

**Comment by sathishmanohar** [comment] 2023-03-15 18:37
Got it. Duplicating tasks in pretty common thing to do in task managers  so looking forward to this.

**Comment by kyeboard** [comment] 2023-08-13 10:53
Closing as duplicate of #76

**Closed by kyeboard** 2023-08-13 10:53 UTC
Labels: enhancement
