### ISSUE TITLE
constant flicker while using the app

### ISSUE THREAD

**Issue by deven367** [kraanzu/dooit#68] opened 2022-08-14 15:43 UTC
I installed the app on my system, 
Python version: 3.10.4
Windows 10 and WSL (Ubuntu 20.04)
There is a constant flicker when I try to create a task. I'm not sure what is causing this issue.

https://user-images.githubusercontent.com/31466137/184544529-3807eb80-8063-4525-a4f9-3a781b6457ad.mp4

**Comment by kraanzu** [comment] 2022-08-14 16:26
Yes actually windows `cmd` is not very good at handling these and might cause some issues.

Maybe try using some other terminal such as [alacritty](https://alacritty.org/) ? Or
I also see that you have linux shells open in other tabs... are they reproducing the same issues?

**Comment by deven367** [comment] 2022-08-15 02:49
Yes, I have the issue on WSL as well.

**Comment by kraanzu** [comment] 2022-08-15 06:51
> Yes, I have the issue on WSL as well.

Hmm.. 
Then it's the terminal's issue. Maybe try some other terminal as I mentioned previously?

> Maybe try using some other terminal such as [alacritty](https://alacritty.org/) ?

**Comment by Gwaenchanayo** [comment] 2022-08-16 04:37
Experiencing the same issue on Linux with St. Does not occur in Alacritty.

**Comment by kraanzu** [comment] 2022-08-16 05:09
> Experiencing the same issue on Linux with St

I can't even run dooit in St, It crashes immediately with:

```
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  3709
  Current serial number in output stream:  4633
```

So I tried [termtyper](https://github.com/kraanzu/termtyper) which is also based on [textual](https://github.com/Textualize/textual)
It ran fine for first few minutes but crashed eventually :(

**Comment by Gwaenchanayo** [comment] 2022-08-16 05:26
> I can't even run dooit in St, It crashes immediately

I'm using [Siduck's build](github.com/siduck/st). Possible it is 'working' for me because of some patch or dependency applied there. 

The umlauts around the window seem to occur when resizing/at different window sizes. 

![Example](https://user-images.githubusercontent.com/102994494/184803795-11056f74-9a0e-4f1d-99f4-65ba61b43263.png)

**Comment by kraanzu** [comment] 2022-08-16 06:26
> Possible it is 'working' for me because of some patch or dependency applied there.

I tried that but no luck :(

> The umlauts around the window seem to occur when resizing/at different window sizes

Tried in alacritty, kitty and xfce-term which all run perfectly without producing umlauts

**Comment by Gwaenchanayo** [comment] 2022-08-16 08:14
> Tried in alacritty, kitty and xfce-term which all run perfectly without producing umlauts 

Yeah; as I said in the first comment - it happens in St but works fine Alacritty.

**Comment by Weissle** [comment] 2022-09-01 14:32
Python 3.10.4
OS: windows10 WSL2 ubuntu18.04.
This problem exists both in alacritty and windows terminal.

**Comment by kraanzu** [comment] 2022-09-01 14:56
Hi @Weissle,

I am using alacritty ( OS: Arch Linux) and I am not facing any such issues. 
Is there a specific condition that makes the app flicker or is it just random?

**Comment by Weissle** [comment] 2022-09-01 15:25
It happens when I begin typing like adding a new project or a task.
Do you use any TUI framework? maybe it is a TUI problem.

**Comment by kraanzu** [comment] 2022-09-01 15:54
>  Do you use any TUI framework? 

Yes, I am using [textual](https://github.com/Textualize/textual)

> maybe it is a TUI problem.

Maybe, but for some people the app is running just fine which makes this odd. Have you tried other terminals? Does that result in similar behavior? 

> It happens when I begin typing like adding a new project or a task.

Well, It has to refresh that time in order to take changes... Does it flicker when you expand/de-expand the tree structure?

**Comment by kraanzu** [comment] 2022-09-01 16:08
Hey @Weissle,

Try this script and see if it flickers ( You can tune the `RATE` variable and see if that makes any difference )
```python
from textual.app import App
from textual.widgets import Static

RATE = 60


class MyApp(App):
    async def on_mount(self):
        self.w = Static("")
        self.message = ">"
        await self.view.dock(self.w)
        self.set_interval(1 / RATE, self.update_screen)

    async def update_screen(self):
        self.message = "=" + self.message
        await self.w.update(self.message)

MyApp.run()
```

I tried increasing the rate and constantly changing the terminal(alacritty)'s size but was not able to reproduce any kind of flicker :)

**Comment by Weissle** [comment] 2022-09-02 00:51
> 

I run this script and it works fine as well as when `RATE = 600`.

**Comment by kraanzu** [comment] 2022-09-02 01:37
>  run this script and it works fine as well as when RATE = 600

Guess I oversimplified this a bit too much lol

> I try dooit today and find that it also flickers when I move the cursor.

What about the other terminals? Does that reproduce the same behavior?

**Comment by Weissle** [comment] 2022-09-02 07:51
> 

Yes. It flickers on windows terminal, cmd, and alacritty.

**Comment by kraanzu** [comment] 2022-09-02 08:15
> Yes. It flickers on windows terminal, cmd, and alacrity.

My bad. I thought you were using Ubuntu itself and not WSL.
That's more like a windows issue, terminals don't generally play well in the case of windows.
I think textual is working to solve the issues on a separate branch but we'll just have to wait for now :(

>  I can sure this is a rendering problem.

Yes, that is definitely the case. The `selfj`s gets highlighted in the video simultaneously, which can only mean one thing.
Guess we'll just have to wait for the new release for the time being :(

**Comment by Weissle** [comment] 2022-09-02 08:16
Sure. Thank you for your response.

**Comment by kraanzu** [comment] 2023-03-02 08:57
I've updated the textual version which should fix things up!
I'll close this issue for now. Feel free to re-open if the issue still persists :(

**Closed by kraanzu** 2023-03-02 08:57 UTC
