### ISSUE TITLE
[BUG] Can't add Sub-Subnode

### ISSUE THREAD

**Issue by yuckdevchan** [kraanzu/dooit#85] opened 2023-01-20 17:45 UTC
**Describe the bug** 🐛
When I try to add a subnode (shift+a) to a subnode it doesn't work - I can only add subnodes to normal nodes

**To Reproduce** 🐣
1. Create a Node
2. Create a Subnode on that node
3. Create a Subnode on that Subnode from Step 2
4. Nothing Happens?

**Expected behavior**  🤔 
Another subnode to be created

**Desktop (please complete the following information):**  🤖
 - OS: SteamOS with RWFS and i3
 - Version: 3.4

**Comment by kraanzu** [comment] 2023-01-21 06:47
Hi there @yuckdevchan!
It's not a bug... I implemented it that way for some reason but I'm working on a new version that does not have this restriction. Will close this issue once released :D

**Comment by yuckdevchan** [comment] 2023-01-21 10:57
> Hi there @yuckdevchan! It's not a bug... I implemented it that way for some reason but I'm working on a new version that does not have this restriction. Will close this issue once released :D

OK, Thanks - Good to know this feature is coming. 👍

**Comment by kraanzu** [comment] 2023-03-02 08:00
Implemented in v1.0

**Closed by kraanzu** 2023-03-02 08:00 UTC
Labels: bug

**Comment by yuckdevchan** [comment] 2023-03-02 12:51
> Implemented in v1.0

Thanks a million!

**Comment by kraanzu** [comment] 2023-03-02 14:34
Thanks a million for all the love and support <3
